version: 2.1

jobs:
  say-hello:

    docker:
      - image: cimg/python:3.8.10
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
                   python bot.py

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
